#!/usr/bin/env bash
# Simple test to verify protobuf login works by checking browser network

echo "=== Testing Protobuf Login in UI ==="
echo ""
echo "Opening browser to http://localhost:3000/login"
echo "Please check browser console for [Protobuf] and [API] logs"
echo ""
echo "Try logging in with:"
echo "  Email: librarian1@library.local"
echo "  Password: librarian123"
echo ""
echo "In browser DevTools (F12):"
echo "  1. Go to Network tab"
echo "  2. Look for POST request to /api/v1/auth/login/"
echo "  3. Check Headers for 'Content-Type: application/x-protobuf'"
echo "  4. Check Console for [Protobuf] logs showing encoding succeeded"
echo ""
echo "Backend logs location:"
echo "  tail -f /media/files/projects/neighborhood-library-platform/backend/logs/django.log"
echo ""
echo "The protobuf implementation is working if you see:"
echo "  ✓ Backend logs show 'Successfully parsed LoginRequest'"
echo "  ✓ Response status is 200 (not 400 or 415)"
echo "  ✓ Response size is 295 bytes (protobuf response)"
