# Generated by Django 4.2.8 on 2026-01-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
