# Generated by hand: make password non-nullable and hash existing empty passwords
from django.db import migrations, models


def set_passwords(apps, schema_editor):
    Member = apps.get_model('core', 'Member')
    from django.contrib.auth.hashers import make_password

    # Hash any existing NULL or empty passwords to the default 'user123'
    for m in Member.objects.filter(password__isnull=True):
        m.password = make_password('user123')
        m.save(update_fields=['password'])
    for m in Member.objects.filter(password=''):
        m.password = make_password('user123')
        m.save(update_fields=['password'])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_member_password"),
    ]

    operations = [
        migrations.RunPython(set_passwords, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default='user123', max_length=255),
        ),
    ]
